### PR TITLE
README: clarify phrasing

### PR DESCRIPTION
**Pull request by GabeAtWork**

### CODE REVIEW

**Comment by enricopolanski** [comment]
I generally try to stray away from punctuation like `-` as it is not used in scientific contexts much.

I am not _that_ opinionated on the matter though, could you give me your 2 cents?

**Comment by GabeAtWork** [comment]
For context I'm don't often read scientific papers. Do you think using parentheses instead would work? e.g. `(we'll call this element _empty_)`

**Comment by enricopolanski** [comment]
I think both can work, as long as we keep this pattern consistent. I'll let you choose and I can merge whatever you prefer.

Maybe, the `-` makes it more readable than parentheses?

**Comment by GabeAtWork** [comment]
@enricopolanski agreed, I think `–` is more readable 👍

**Comment by GabeAtWork** [comment]
Thank you for taking the time to look at this 😊

**Comment by enricopolanski** [comment]
Thank you for your contribution.

**Pull request merged**
