### PR TITLE
Add table of content

### PR DESCRIPTION
**Pull request by vinassefranche**
I always felt this was missing and had a hard time finding the information I wanted so I added this table of content.
I hope you'll find it useful

### CODE REVIEW

**Comment by vinassefranche** [comment]
you can have a look at the result [here](https://github.com/vinassefranche/functional-programming/tree/add-table-of-content), by the way

**Comment by enricopolanski** [comment]
Hi @vinassefranche in the past @gcanti used to build the TOC with [doctoc](https://github.com/thlorenz/doctoc), but this has been deprecated because GitHub generates automatically a TOC for readme files, see image below, so I'm not sure about duplicating this behavior.

image

**Comment by vinassefranche** [comment]
@enricopolanski I did not know about this github TOC. Thanks for telling me and, yes, this makes my P.R. pretty pointless... I closing it.

**Comment by enricopolanski** [comment]
@vinassefranche I would not say it was completely pointless. Some people may navigate the document through their code editor and there you don't have GitHub's TOC so I have never been completely sure.

**Comment by vinassefranche** [comment]
@enricopolanski in that case, maybe I can add the TOC but collapsed by default with something like this:

<details>
  <summary><h2>Table of Content</h2></summary>
  
  ...
</details>

**Pull request closed without merging**
